name: Pipelines

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs: # groups the jobs to be executed in this workflow
  build: # defines a job called build
    name: 🔨 Build, 🔍 Lint, 🧪 Unit # [optional] name of the job
    runs-on: ubuntu-latest # the job will be executed on ubuntu runner. Other include: Microsoft Windows & MacOS runners
    steps: # groups together all the steps that run in build job

      # Checks out code from the VCS to the runner
      - name: Checkout Code # [optional] specifies the name of the step
        uses: actions/checkout@v3 # specifies which action and version to execute ie. checkout@v3

      # Setup JDK Version 11 in the runner
      - name: 'Set up latest Oracle JDK 17'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17

      # Allow permissions to make gradle executable - This can removed by adding the gradlew file permission
      # directly into the repository using `git update-index --chmod=+x gradlew`
      - name: Make gradle executable
        run: chmod +x ./gradlew

      # Execute gradle build command with stacktrace flag
      - name: Build with gradle
        run: ./gradlew build lint testDebugUnitTest --stacktrace # Execute gradle script to build project

      - name: Generate lint report
        uses: actions/upload-artifact@v3.1.2 # Uses upload-artifact@v2 action to upload lint report artifact
        with: # Define extra parameters
          name: Lint Report # Name of the artifact to be uploaded
          path: app/build/reports/lint-results-debug.html # Specifies the path where the artifact to be uploaded is located

      - name: Generate test report # Generates tests reports as an artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Unit Test Reports
          path: app/build/reports/tests/testDebugUnitTest/

  androidTest:
      # Faster, but MacOS costs 8 ct/min instead of 0.8 ct/min of on Linux.
      # Unfortunately, `DataCapturingServiceTest.testDisconnectReconnect` fails on linux stack.
      # But as this is a public repository, Github Actions are currently free of charge.
      #runs-on: macos-latest # as recommended in `actions/android-emulator-runner`

      # But we had to add `free-disk-space` to fix emulator flakiness. It only runs on ubuntu.
      runs-on: ubuntu-latest

      timeout-minutes: 55

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'

        # Add caching to speed up connected tests below (see `actions/android-emulator-runner`)
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v3

        - name: Build projects before running emulator
          run: ./gradlew packageDebugAndroidTest

        - name: Connected tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 28
            arch: x86_64
            disable-animations: true
            disk-size: 6000M
            heap-size: 600M

            script: ./gradlew app:connectedCheck

        - name: Upload test reports
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Ui Test Reports
            path: '**/build/reports/androidTests'